version: '3.9'

services:

  db:
    image: postgres:13-alpine
    restart: always

    environment:
      POSTGRES_USER: "YEGOR"
      POSTGRES_PASSWORD: "QWERT"
      POSTGRES_DB: "app"

    ports:
      - "5432:5432"
